services:
  db:
    image: postgres
    container_name: db_prod
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - ./.postgres-data:/var/lib/postgresql/data

  app:
    build:
      context: .
      dockerfile: compose/production/Dockerfile
    container_name: app_prod
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - db