
name: CI

on:
  push:
    branches:
      - develop
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install taskipy
          pip install ruff

      - name: Run tests
        env:
          DATABASE_URL: postgresql://user:password@db:5432/mydatabase
          SECRET_KEY: mysecretkey
          ALGORITHM: HS256
          ACCESS_TOKEN_EXPIRE_MINUTES: "30"
          POSTGRES_USER: user
          POSTGRES_PASSWORD: password
          POSTGRES_DB: mydatabase
        run: task test
